Use ResponseLifecycle from core http-server
micronaut-projects/micronaut-servlet pull request #837
Opened 2024-11-20 08:56 UTC by yawkat

Instead of servlet-specific body encoding logic, use the ResponseLifecycle introduced in core by https://github.com/micronaut-projects/micronaut-core/pull/11342 (pending review). Then we only have to take care of writing the ByteBody to the servlet response.

Some other related changes:

- Improved async reading/writing support, deprecate StreamedServletMessage
- Rework HttpResponse lifecycle management: Core mostly expects HttpResponseFactory to return new, independent responses, but servlet returned views of the same ServletHttpResponse each time (with shared headers and such). New approach is to have only the latest HttpResponse backed by the real ServletHttpResponse, any previous responses are copied snapshots
- Deprecate and stop using ServletResponseEncoder, it is replaced by core ResponseBodyEncoder.

These changes fix all the remaining TCK failures that relate to response handling, except for FilterProxyTest.

2025-02-10 12:28 UTC, graemerocher commented
@yawkat tests failing?

2025-02-11 08:30 UTC, yawkat commented
definitely an issue here, unfortunately only in the jetty native tests so a bit hard to debug.

2025-02-11 08:41 UTC, sdelamo requested changes

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/encoders/FileEncoder.java
> +@Deprecated
```suggestion
@Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/encoders/AbstractFileEncoder.java
> +@Deprecated
```suggestion
@Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/StreamedServletMessage.java
> +@Deprecated
```suggestion
@Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/ServletResponseEncoder.java
> +@Deprecated
```suggestion
@Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpResponse.java
> +    @Deprecated
```suggestion
    @Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/ServletExchange.java
> +    default ServletHttpResponse<Res, ?> createResponse() {
why are we creating a new method? just for renaming?

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/ServletExchange.java
> +     * @since 4.13.0
```suggestion
     * @since 5.1.0
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpResponse.java
> +     * @return A future that completes when the body is fully written
```suggestion
     * @return A future that completes when the body is fully written
     * @since 5.1.0
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/DefaultServletExchange.java
> +@Deprecated
```suggestion
@Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-11 08:41 UTC, sdelamo commented on http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyFileTypeHandlerSpec.groovy
> +        response.code() == HttpStatus.INTERNAL_SERVER_ERROR.code
should not we respond 404 instead?

2025-02-11 08:41 UTC, sdelamo commented on http-poja-common/src/main/java/io/micronaut/http/poja/PojaHttpServerlessApplication.java
> +     * @return {@code true} iff more requests can come in, {@code false} when the connection should
```suggestion
     * @return {@code true} if more requests can come in, {@code false} when the connection should
```

2025-02-11 08:41 UTC, sdelamo commented on http-poja-apache/src/main/java/io/micronaut/http/poja/apache/ApacheServletHttpRequest.java
> +        if (connection != null && connection.getValue().equalsIgnoreCase("close")) {
extract constant for "close"

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
> +            }
it would be good to extract this into its own method and write a test for the logic.

2025-02-11 08:41 UTC, sdelamo commented on servlet-core/src/main/java/io/micronaut/servlet/http/encoders/SystemFileEncoder.java
> +@Deprecated
```suggestion
@Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-11 08:41 UTC, sdelamo commented on servlet-engine/src/main/java/io/micronaut/servlet/engine/ServletStreamPublisher.java
> + * @since 4.13.0
```suggestion
 * @since 5.1.0
```

2025-02-11 11:48 UTC, graemerocher commented
still failing

2025-02-14 07:06 UTC, yawkat commented on servlet-core/src/main/java/io/micronaut/servlet/http/encoders/StreamFileEncoder.java
> +@Deprecated
```suggestion
@Deprecated(forRemoval = true, since = "5.1.0")
```

2025-02-14 07:12 UTC, yawkat commented on http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyFileTypeHandlerSpec.groovy
> +        response.code() == HttpStatus.INTERNAL_SERVER_ERROR.code
This is what core does. The reason is that the controller explicitly returns a file that does not exist, which is a programmer error, not a user error

2025-02-14 07:14 UTC, yawkat commented on servlet-core/src/main/java/io/micronaut/servlet/http/ServletExchange.java
> +    default ServletHttpResponse<Res, ?> createResponse() {
This one actually creates a response instead of just returning an existing one

2025-02-14 07:36 UTC, yawkat commented
The build finally passes, but @sdelamo I had to revert the patch tomcat upgrade

2025-02-14 17:16 UTC, sdelamo approved these changes

2025-02-14 18:24 UTC, graemerocher approved these changes

2025-02-14 19:49 UTC, merged